name: star watcher

on:
  watch:
    types: started

jobs:
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          TZ=Asia/Shanghai date "+%y-%m-%d %H:%M:%S" | xargs -I {} echo "[{}] 被点star了"
